# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
GMAIL_USERNAME: Gmail_user_name
GMAIL_PASSWORD: Gmail_password

#Sending email to this ID when a user filling Contact-Us form.
CONTACT_ADMIN_EMAIL: Your_Email_Address

#Enter information for creating default/Admin user
ADMIN_NAME: Admin_name
ADMIN_EMAIL: Admin_email
ADMIN_PASSWORD: Admin_password
ADMIN_CITY: Admin_city
ADMIN_STATE: Admin_state
ADMIN_ZIPCODE: Admin_zipcode
ADMIN_ACCOUNT: Admin_account
ADMIN_PHONE: Admin_phone
ADMIN_FAX: Admin_fax
ADMIN_ADDRESS: Admin_address
